name: "Mr. Shafiei's Classes"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown_ext: markdown,mkdown,mkdn,mkd,md
highlighter: pygments
pygments: true
baseurl:  
permalink: pretty
kramdown:
    input: GFM



  

