name: "Bobak"
markdown: redcarpet
pygments: true
permalink: /:categories/:title
baseurl: /classes



navigation:
- title: Assignments
  text: Assignments
  url: /assignments
  
- title: Calendar
  text: Calendar
  url: /calendar
  
- title: Syllabus
  text: Syllabus
  url: /syllabus
  
- title: Blog
  text: Blog
  url: /blog