name: "Mr. Shafiei's Classes"
markdown: redcarpet
pygments: true
permalink: /:categories/:title
baseurl: /classes



navigation:
- title: Assignments
  text: Assignments
  url: /pages/assignments
  
- title: Calendar
  text: Calendar
  url: /pages/calendar
  
- title: Syllabus
  text: Syllabus
  url: /pages/syllabus
  
- title: Blog
  text: Blog
  url: /pages/blog