name: "Bobak"
markdown: redcarpet
pygments: true
permalink: pretty
baseurl: /classes



navigation:
- title: Assignments
  text: Assignments
  url: /assignments
- title: Calendar
  text: Assignments
  url: /calendar
- title: Syllabus
  text: Syllabus
  url: /syllabus
- title: Blog
  text: Blog
  url: /blog