name: "Bobak"
markdown: redcarpet
pygments: true
permalink: pretty



navigation:
- text: Assignments
  url: /assignments
- text: Calendar
  url: /calendar
- text: Syllabus
  url: /syllabus
- text: Blog
  url: /blog